is_debug: true
service:
  type: port
  bind_ip: 0.0.0.0
  port: 30001
  metrics_port: 9090
  domain:
redis:
  host: redis
  port: 6379
  password:
  db: 0
postgresql:
  host: postgresql
  port: "5432"
  database: postgres
  username: postgres
  password: admin123
email:
  sender: e-cost.by
  address:
  password:
yandex:
  bucket:
